### ISSUE TITLE
Fixtures are unavailable causing tests to fail

### ISSUE THREAD

**Issue by OR13** [microsoft/bbs-node-reference#11]
<img width="1198" alt="Screen Shot 2023-03-18 at 2 50 49 PM" src="https://user-images.githubusercontent.com/8295856/226134567-762a8461-54e3-4bfc-96e9-27074660c1f0.png">

In fixture.test.ts, after fetching test vectors:

<img width="992" alt="Screen Shot 2023-03-18 at 2 53 46 PM" src="https://user-images.githubusercontent.com/8295856/226134694-cdd343f5-9b3f-4b8e-97fd-e236eb48d606.png">

**Comment by christianpaquin** [comment]
The fixture tests changed from the previous version, and my fixture fetch scripts only checks if the directory exists before downloading them, so you probably have the old files (and missing some new ones). Delete the `fixtures` folder, and re-run, that should do it. (I'm taking note to improve the behavior of the script...)

**Comment by OR13** [comment]
Yes, that worked for me:

```
rm -rf ./fixtures
npm i
npm t
```

**Comment by christianpaquin** [comment]
I have a TODO to add CI, let me bring it top of the priority list...

**Comment by christianpaquin** [comment]
I just put in my boilerplate CI file (and now am just noticing your comment). I like your coverage and badge, so I'll gladly accept a PR to improve this repo!
